---
title: "Lab 5"
author: "Kyle Belanger"
date: "2/5/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning = FALSE, message = FALSE)
```

# Load Libraries

```{r Load Libraries}
library(magrittr) #pipes
library(ggplot2) #ploting 
library(dplyr)  # data manipulation
library(tidyr) # tidy data
library(lubridate) #work with dates
library(stringr) # manipulate strings
library(plotly) #interactive graphs
```



```{r}
ds_yoy <- readxl::read_xlsx(path = "../../data_public/Tableau 10 Training Practice Data.xlsx"
                        ,sheet = "09 - Patient Volume YOY Change"
                        )

ds_yoy %>% glimpse()

```


# Transform Data

```{r}
yoy_new_varnames <- c("date", "patient_visits")

names(ds_yoy) <- yoy_new_varnames

ds_yoy1 <- ds_yoy %>% 
  #pull month and year from the current date column
  mutate(  
    month = factor(month(ds_yoy$date),
                   levels  = c(1:12)
                   ,labels = month.name[1:12])
    ,year = year(ds_yoy$date)
  ) %>% 
  #select all columns but date
  select(-date) %>% 
  #pivot date so each month has 2015 and 2016 data next to each other
  pivot_wider(names_from   = year
              ,values_from = patient_visits) %>% 
  #add percent difference column
  mutate(
    percent_difference = round(((`2016` - `2015`)/`2015`)*100,1)
  )

```

# Graph GGPlot YOY (Deviation Line)

```{r}
#label function to add perecnt sign to graph
percent_formatter <- function(x) {
  return(paste(format(x, nsmall = 1),"%"))
}

g_yoy1 <- ds_yoy1 %>% 
    ggplot(mapping = aes(x = month, y = percent_difference, group = 1)) +
  geom_line(color = "#4e79a7", size = 1) +
  geom_point(color = "#4e79a7", size = 2) +
  geom_hline(yintercept = 0, linetype = 'dashed') +
  ggrepel::geom_label_repel(aes(label = percent_difference)) +
  theme_bw() +
  theme(
    axis.text.x = element_text(
      angle  = 45
      ,hjust = 1
      )
  ) +
  labs(
    title = "Percent Change of Hospital Emergency Department Patient Volume by Month,  
2016 compared with 2015"
    ,x = NULL
    ,y = "YOY Patient Visit Percent Change"
  ) +
  scale_y_continuous(breaks = seq(-6,7,1), labels = percent_formatter)


g_yoy1
```

# YOY Plotly

```{r}
g_yoy2 <-  ds_yoy1 %>% 
  plot_ly(x = ~month, y = ~percent_difference, type = "scatter", mode = "line",
          hovertemplate = paste("Month : %{x}"
                                ,"<br>Difference : %{y}%") 
          ) %>%
  layout(
    title = "Percent Change of Hospital Emergency Department Patient Volume by Month,  
2016 compared with 2015"
    ,xaxis = list(title = "")
    ,yaxis = list(title = "YOY Patient Visit Percent Change")
  )

g_yoy2
  
  
```

# Bar Graph

## Import Data 

```{r}

# readxl::excel_sheets(path = "../../data_public/Tableau 10 Training Practice Data.xlsx")
# Used to read sheet names, makes user error less likly

ds <- readxl::read_xlsx(path = "../../data_public/Tableau 10 Training Practice Data.xlsx"
                        ,sheet = "08 - Department FTE Counts" 
                        )


# Glimpse at both Raw data sets

ds %>% glimpse()  # Glimpse at data

```

# Transform Data Set FTE

```{r}
new_varnames <- c("department" , "budgeted_fte" , "actual_fte"  )

names(ds) <- new_varnames 

ds1 <-  ds %>% 
          mutate(
              off_by_fte = actual_fte - budgeted_fte
          )

```

# Graph FTE Ggplot (Deviation Bar)

```{r}
g1 <- ds1 %>% 
      ggplot(mapping = aes(x = reorder(department, -off_by_fte) , y = off_by_fte)) +
      geom_col(fill = "#4e79a7") +
      geom_hline(yintercept = 0) +
      theme_bw() +
      scale_y_continuous(limits = c(-80,30), breaks = seq(-80,30,10)) +
      labs(
        x      = NULL
        ,y     = "FTE Off By"
        ,title = "Deviation of Actual FTE to Budgeted FTE \nby Department"
      )
      
g1
  
  
```

# Graph FTE Plotly

```{r}
ds2 <- ds1 %>%  arrange(-off_by_fte)


g2 <- ds2 %>% 
  
  plot_ly(x = ~department, y = ~off_by_fte,  type = "bar"
          ,hovertemplate = paste("Department : %{x}"
                                 ,"<br>FTE Off By : %{y}")) %>% 
  layout(
    automargin = T
    ,title = "Deviation of Actual FTE to Budgeted FTE \nby Department"
    ,xaxis = list(title = ""
                 ,categoryorder = "array"
                 ,categoryarray = ~off_by_fte
            )
    ,yaxis = list(title = "FTE Off By"
                  ,range = c(-85,35) # set limits
                  ,dtick = 10  #set distance between ticks
             )
  )
g2
```

