---
title: "Lab 09"
author: "Kyle Belanger"
date: "2/26/2020"
output: 
  html_document:
    toc: true
    toc_float: true
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r}
rm( list = ls(all = TRUE)) # to clean the environment
cat("\014") # to clean the console

```

# Load Packages

```{r}
library(magrittr) # pipes
library(dplyr)    # wrangling
library(ggplot2)  # graphing
library(tidyr)    # pivoting
library(stringr)  # manipulate strings
library(gghighlight) # hightlight certin points

```

# Source Files

```{r}
source("../functions/helper_functions.R")
```


# Load Data

```{r}

# readxl::excel_sheets("../../data_public/raw/Tableau 10 Training Practice Data.xlsx")


ds_raw <- readxl::read_xlsx("../../data_public/raw/Tableau 10 Training Practice Data.xlsx"
                            ,sheet ="04 - Clinic Patients Metrics" )

ds_raw %>%  glimpse()


```

# Clean Names

```{r}
ds0 <-  ds_raw
colnames(ds0) <- sapply(colnames(ds0), clean_names)

```

# Histogram

```{r}
g1 <- ds0 %>% 
  ggplot(aes(x = age)) +
  geom_histogram(binwidth = 10, color = "white", fill = "#26456E") +
  scale_x_continuous(breaks = seq(20,90,5)) +
  theme_bw() +
  labs(
    x = "Age"
    ,y = "Number of Patients"
    ,title = "Age Distributions of Clinic Patients"
  )
  
g1
```

# Scatter Plot

```{r}

text <- ""

ds1 <- ds0 %>% 
  mutate( bmi = weight_kg/(height_cm/100)^2) 

g2 <- ds1 %>% 
  ggplot(aes(x = bmi, y = bp_systolic)) +
  geom_point(aes(color = bmi >= 30), shape = 1, size = 3, show.legend = FALSE) +
  geom_hline(yintercept = 140, linetype = "dashed", color = "grey") +
  geom_text(aes(5,140, label = "High Blood Pressure", vjust = -0.5)
            ,color = "darkgrey") +
  geom_vline(xintercept = 30, linetype = "dashed", color = "grey") +
  geom_text(aes(30,65, label = "Obese", angle = 90, vjust = -0.5) 
            ,color = "darkgrey") +
  geom_smooth(method = "lm", se = FALSE, fullrange = TRUE, color = "gray") +
  scale_x_continuous(breaks = seq(0,50,5), limits = c(0,50)) +
  scale_y_continuous(breaks = seq(0,200,20), limits = c(60,200)) +
  labs(
    x = "BMI"
    ,y = "BP Systolic"
    ,title = "Correlation of Clinic Patients' \nBody Mass Index (BMI) and Systolic Blood Pressure"
  ) +
  scale_fill_manual(values = c("#7B848F", "#FC7D0B"), aesthetics = "color") +
  theme_bw()

g2



```

# Graphing Function

This function allows for graphing any two of the continuous variables against each other.  It also allows for highlighting one or both of the variables and setting the Quantailes to highlight.

```{r}
create_graph <- function(ds,measure1,measure2, probs = NULL, highlight = NULL) {
  stats <- ds %>% select(c(measure1,measure2)) %>% 
            sapply(function(x) c(
                        mean     = round(mean(x),1)
                        ,std_dev = round(sd(x),1)
                    ))
  names_to_title = function(x) {
    x <- str_replace_all(x,"_"," ")
    x <- str_to_title(x)
  }
  title1 = names_to_title(measure1)
  title2 = names_to_title(measure2)
  
  if(!is.null(probs)) {
  quant <- ds %>% 
    select(c(measure1,measure2)) %>% 
    summarise_all(list(quantile), probs = probs) 
  }
  
  
  g <- ds %>% ggplot(aes_string(x = measure1, y = measure2)) +
    geom_point() +
    geom_rug() +
    geom_vline(xintercept = stats[1,1]) +
    geom_vline(xintercept = c(stats[1,1] + stats[2,1],stats[1,1] - stats[2,1])
               ,alpha = 0.3) +
    geom_hline(yintercept = stats[1,2]) +
    geom_hline(yintercept = c(stats[1,2] + stats[2,2],stats[1,2] - stats[2,2])
               ,alpha = 0.3) +
    labs(
      title = glue::glue("{title1} : Mean = {stats[1,1]} SD = {stats[2,1]}"
                         ,"\n{title2} : Mean = {stats[1,2]} SD = {stats[2,2]}")
      ,x = title1
      ,y = title2
    )
  
  if(!is.null(probs) && is.null(highlight)) {
    g <-  g + gghighlight(.data[[measure1]] > as.numeric(quant[1,1]) |
                          .data[[measure2]] > as.numeric(quant[1,2]) )
    return(g)
  } else if (!is.null(probs) && highlight == 1 ) {
    g <-  g + gghighlight(.data[[measure1]] > as.numeric(quant[1,1])) 
    return(g)
  }  else if (!is.null(probs) && highlight == 2 ) { 
    g <-  g + gghighlight(.data[[measure2]] > as.numeric(quant[1,2])) 
    return(g)
  } else {
    return(g)
  }
  
}


create_graph(ds0,"bp_diastolic","bp_systolic" ,probs = 0.90)
create_graph(ds0,"age","weight_kg", probs = 0.8, highlight = 2)
create_graph(ds0,"age","weight_kg", probs = 0.8, highlight = 1)
create_graph(ds0,"height_cm","weight_kg")

```

