---
title: "Lab 4"
author: "Kyle Belanger"
date: "1/28/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning = FALSE, message = FALSE)
```

# Load Libraries

```{r}
library(magrittr) #pipes
library(ggplot2) #ploting 
library(dplyr)  # data manipulation
library(tidyr) # tidy data
library(lubridate) #work with dates
library(stringr) # manipulate strings
library(plotly)
```

# Import Data

```{r}
#readxl::excel_sheets(path = "../../data_public/Tableau 10 Training Practice Data.xlsx")  
# Used to read sheet names, makes user error less likly

ds <- readxl::read_xlsx(path = "../../data_public/Tableau 10 Training Practice Data.xlsx"
                        ,sheet = "05 - Flu Occurrence FY2013-2016"
                        )
ds %>% glimpse()  # Glimpse at data
```

# Transform Data

```{r}
#reformat column names - 

format_names <- function(x) {
  #Fucntion to set all names to lower case, and strip unneeded characters
  x <- tolower(x)
  x <- str_replace_all(x,c(
                       " "         = "_"
                      ,"\\(\\+\\)" = "pos"  #regualr experssion to match (+)
                      ,"\\("       = ""
                      ,"\\)"       = ""
                      ,"\\%"       = "pct"
                      )
                  ) #set each pattern equal to replacement
                }

#run the format name function on all names from DS
colnames(ds) <- sapply(colnames(ds),format_names)    




# split date time
ds1 <- ds %>% mutate(
        #create month column, then set factors and labels to start fiscal year in Oct
        month = month(ds$date)
        ,month = factor(month
                        ,levels = c(10:12, 1:9)
                        ,labels = c(month.abb[10:12],month.abb[1:9]))
       ,year = year(ds$date)
        ,date_adjustment = ifelse(month(ds$date) >= 10, 1,0 )
        ,fiscal_year = factor(year + date_adjustment)
        #convert % Pos from decmial to pct
        ,pct_tests_pos_for_influenza = round(pct_tests_pos_for_influenza * 100, digits = 0)
        )

ds1 %>% glimpse()
```

# Graphs

```{r}
                                  

g1 <- ds1 %>% 
    ggplot(aes(x = month, y = pct_tests_pos_for_influenza, color = fiscal_year
               ,group = fiscal_year)) +
  geom_line() +
  labs(
    x  = NULL
    ,y = "% Tests (+) for Influenza"
    ,color = NULL
    ,title = "Flu Viral Surveillance: % Respiratory Specimens Positive for Influenza \nOctober - September \nFor Flu Seasons 2013 - 2016"
  ) +
  theme_classic() +
  scale_y_continuous(limits = c(0,40), breaks = seq(0,40,5)) +
  scale_color_manual(values = c("#a6611a","#dfc27d","#80cdc1","#018571"))

g1
```

# plotly

```{r}



g2 <- ds1 %>% 
    plot_ly(x = ~month, y = ~pct_tests_pos_for_influenza, type = "scatter", mode = "lines" 
            ,color = ~fiscal_year
            ,colors = c("#a6611a","#dfc27d","#80cdc1","#018571")
            , hoverinfo = 'y') %>% 
    layout(xaxis = list(
                        title = ""
                    )
           ,yaxis = list(
                        title = "% Tests (+) for Influenza"
                    )
           ,title = "Flu Viral Surveillance: % Respiratory Specimens Positive for Influenza"
           ,legend = list(
                      x = 100
                      ,y = 0.5
                      )   
           
           )

g2
```


