---
title: "Lab 8 Box and Whisker"
author: "Kyle Belanger"
date: "2/18/2020"
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning = FALSE, message = FALSE)
```

# Load Libraries

```{r Load Libraries}
library(magrittr) #pipes
library(ggplot2) #ploting 
library(plotly) #interactive graphs
library(dplyr) #data man
```

# Load Data

```{r}
ds_clinic <- readxl::read_xlsx(path = 
                           "../../data_public/raw/Tableau 10 Training Practice Data.xlsx"
                        ,sheet = "12 - Clinic Patients Demogr"
                        )
ds_readmission <- readxl::read_xlsx(path = 
                           "../../data_public/raw/Tableau 10 Training Practice Data.xlsx"
                        ,sheet = "06 - Patient Readmission Days"
                        )


ds_clinic %>% glimpse()
ds_readmission %>% glimpse()
```

# Join Data Sets

```{r}

ds_combine <- ds_clinic %>% 
  left_join(ds_readmission)

```


# Box Plot

```{r}
g1 <- ds_clinic %>% 
  ggplot(aes(x = Race, y = Age)) +
  stat_boxplot(geom = "errorbar", coef = 100) + #used to draw the error bars
  geom_boxplot(coef = 100, color = "black", fill = "#4e79a7") +  #coef extends whiskers,                                                    picked a high number to match tabaleau
  geom_count(fill         = "red" 
             ,color       = "black"
             ,alpha       = 0.5
             ,shape       = 21
             ,show.legend = FALSE ) +
  scale_x_discrete(labels = c("As" = "Asian", "B" = "Black", "H" = "Hispanic"
                              ,"W" = "White")) +
  scale_y_continuous(breaks = seq(0,90,10), limits = c(30,90)) +
  theme_classic() +
  theme(panel.grid.major.y = element_line(color = "grey")) +
  labs(
    title = "Age Distribution of Cardiovascular Clinic Patients by Race"
    ,x = NULL
    ,y = "Age"
  )
  

g1

```

# Box Plot Readmissions

```{r}
g2 <- ds_combine %>% 
  ggplot(aes(x = Race ,y = `Number of days to readmission`)) +
  stat_boxplot(geom = "errorbar") +
  geom_boxplot( color           = "black"
                ,fill           = "#4e79a7"
                ,alpha          = 0.7
                , outlier.shape = NA
                ) +
  geom_count(fill         = "red" 
             ,color       = "black"
             ,alpha       = 0.5
             ,shape       = 21
             ,show.legend = FALSE 
             ) +
  scale_x_discrete(labels = c("As" = "Asian", "B" = "Black", "H" = "Hispanic"
                              ,"W" = "White")) +
  theme_classic() +
  theme(panel.grid.major.y = element_line(color = "grey")) +
  labs(
    title = "Day to Readmission of Cardiovascular Clinic Patients by Race"
    ,x = NULL
    ,y = "Age"
  )
  


g2

```

